# Generated by Django 4.1 on 2022-08-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="about_myself",
            field=models.TextField(default="Bio", max_length=500),
        ),
    ]
